---
abstract: 'Service Monitoring using AnyEvent'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Monitor
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  AnyEvent: 0
  Method::Signatures::Simple: 0
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/clkao/AnyEvent-Monitor.git
version: 0.32
